force-app/main/default/objects/Producto__c/Producto__c.object-meta.xml
<CustomObject>
    <description>Objeto que almacena los diferentes registros de comida del restaurante</description>
    <label>Producto</label>
    <nameField>
        <label>Nombre del producto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Productos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Producto__c/fields/Imagen__c.field-meta.xml
<CustomField>
    <fullName>Imagen__c</fullName>
    <label>Imagen</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Producto__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Precio</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SearchAvailableProducts.cls
/**
 * @author            : Fernando M. Acosta P.
 * @Equipo            : CRM
 * @last modified on  : 03-12-2025
 * @last modified by  : Fernando M. Acosta P.
 * @Descripción       : Clase apex para la consulta de productos disponibles
 **/
public without sharing class SearchAvailableProducts {
    @AuraEnabled(cacheable=true)
    public static List<Producto__c> getProducts(){
        try {
            List<Producto__c> products = [SELECT Id, Name, Descripcion__c, Precio__c, Imagen__c FROM Producto__c WHERE Status__c = true];
            return products;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage()+e.getStackTraceString());
        }
    }
}